# -*- coding: utf-8 -*-
"""
/***************************************************************************
 InterpolationValidation
                                 A QGIS plugin
 leave one out validation for the interpolation method thinplatespline (tin) from the SAGA console
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2021-05-23
        copyright            : (C) 2021 by Johannes Ritter
        email                : 
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Johannes Ritter'
__date__ = '2021-05-23'
__copyright__ = '(C) 2021 by Johannes Ritter'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load InterpolationValidation class from file InterpolationValidation.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .leaveoneout_tpstin import InterpolationValidationPlugin
    return InterpolationValidationPlugin()
